[config]
schemaVersion = "0.0.1"

[package]
namespace = "Evaisa"
name = "Runtime_Inspector"
versionNumber = "0.0.1"
description = "Runtime hierarchy and inspector utility"
websiteUrl = "https://github.com/EvaisaDev/LCRuntimeInspector"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
Rune580-LethalCompany_InputUtils = "0.6.1"
Evaisa-FixPluginTypesSerialization = "1.1.1"
Evaisa-HookGenPatcher = "0.0.5"

[build]
icon = "icons/icon.png"
readme = "../../README.md"
outdir = "../dist"

[[build.copy]]
source = "../bin/Release/netstandard2.1/evaisa.runtime_inspector.dll"
target = "BepInEx/plugins/Runtime_Inspector/"

[[build.copy]]
source = "bundles"
target = "BepInEx/plugins/Runtime_Inspector/bundles"

[[build.copy]]
source = "../../LICENSE"
target = "/"


[publish]
repository = "https://thunderstore.io"
communities = [ "lethal-company", ]
[publish.categories]
lethal-company = [ "tools", "bepinex", "misc", "clientside", ]


